### GET USERS

GET http://localhost:3000/users  

### POST USER

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John Doe",
    "username": "john_doe"
}

### LIST USERS

GET http://localhost:3000/users
